name: Go Format Check

on:
  push:
    branches:
      - go

jobs:
  gofmt:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.1'

    - name: Run gofmt
      run: |
        gofmt -l -w .
        if [ -n "$(git status --porcelain)" ]; then
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "🎨 Apply gofmt changes"
          git push origin go
        fi
